### ISSUE TITLE
Ombi

### ISSUE THREAD

**Issue by foXaCe** [FayzB/Package-APKs#1]
Bonjour,

d'abord bravo pour les traductions, pourrait faire l'app Ombi a temps perdu s'il te plait ?

https://play.google.com/store/apps/details?id=com.tidusjar.Ombi&hl=en_US

**Comment by FayzB** [comment]
Bonjor envoie moi l'app que je regarde ça

**Comment by foXaCe** [comment]
Bonjour, tu as le lien dans mon comment
